<<<<<<< HEAD:med-connect/src/app/layout.jsx
import { Geist, Geist_Mono } from "next/font/google";
=======
import type { Metadata } from "next";
>>>>>>> 1173f54 (Remove the unwanted api integration):med-connect/src/app/layout.tsx
import "./globals.css";

<<<<<<< HEAD:med-connect/src/app/layout.jsx
// Metadata object (Ab bina type annotation ke)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Providers wrapper */}
        <Providers>{children}</Providers>
      </body>
=======
export const metadata: Metadata = {
  title: "MedConnect - Your Healthcare Platform",
  description:
    "MedConnect is a modern healthcare platform that connects patients with doctors for seamless medical appointments and health management.",
  keywords: [
    "healthcare",
    "medical",
    "appointments",
    "doctors",
    "patients",
    "telemedicine",
  ],
  authors: [{ name: "MedConnect Team" }],
  openGraph: {
    title: "MedConnect - Your Healthcare Platform",
    description:
      "Connect with doctors, manage appointments, and access your medical records all in one place.",
    type: "website",
    locale: "en_US",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
>>>>>>> 1173f54 (Remove the unwanted api integration):med-connect/src/app/layout.tsx
    </html>
  );
}
